# node use to build
FROM node:alpine as builder

ENV PROJECT_ENV production
ENV NODE_ENV production

COPY package*.json /app/

WORKDIR /app

RUN npm install 
COPY . /app

RUN npm run build

# small size base image
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /app/build

EXPOSE 80

# start nginx，daemon off because docker need run after start
CMD ["nginx", "-g", "daemon off;"]